### ISSUE TITLE
worng datatype skeletonrequest_field

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_Skeletonrequest#2]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.x

#### Summary

Wrong datatype  `skeletonrequest_field` int(11) NOT NULL
in install.sql

#### Current behavior
Custom sql config not map 
Should be varchar

#### How to reproduce

Install skeletonrequest modul and apply custom config

**Comment by Praesidiarius** [comment]
fixed in latest master-dev
